# Generated by Django 5.0.3 on 2025-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_currency_profile_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transaction_scope',
            field=models.CharField(choices=[('International Transfer', 'International Transfer'), ('Local Transfer', 'Local Transfer'), ('Check Deposite', 'Check Deposite')], default='Local Transfer', max_length=50),
        ),
    ]
